export const urls = {
  login: 'login',
  admin: 'admin',
  adminUsers: 'users',
  systemSettings: 'system-settings',
  workshops: 'workshops',
  woodNamings: 'wood-namings',
  referenceBook: 'reference-book',
  dryers: 'dryers',
  dryer: 'dryer',
  dashboard: 'dashboard',
  warehouse: 'warehouse',
  arrival: 'arrival',
  shipment: 'shipment',
  workshop: 'workshop',
  day: 'day',
  timeRange: 'time-range',
  delete: 'delete',
  suppliers: 'suppliers',
  buyers: 'buyers',
  personsInCharge: 'persons-in-charge',
} as const
