export const urls = {
  login: 'login',
  admin: 'admin',
  adminUsers: 'users',
  systemSettings: 'system-settings',
  workshops: 'workshops',
  woodNamings: 'wood-namings',
  referenceBook: 'reference-book',
  dryers: 'dryers',
  dryer: 'dryer',
  dashboard: 'dashboard',
  warehouse: 'warehouse',
  arrival: 'arrival',
  shipment: 'shipment',
  vault: 'vault',
  dryWoodVault: 'dry-wood',
  wetWoodVault: 'wet-wood',
  workshop: 'workshop',
  day: 'day',
  timeRange: 'time-range',
} as const
